name: Docker Image CI

on:
  push:
    branches: [master]
  # this is a security vulnerability, pwndocker
  # pull_request:
  #   branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          image_name: pepsipu/pwn
          tag: latest
        run: |
          docker build . --file Dockerfile --tag $image_name:$tag
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWD }}
          docker push $image_name:$tag
